-- Users and Route Scopes baseline for Day-1
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL, -- ADMIN, APPROVER, REVIEWER, USER
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS route_scopes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  route_pattern VARCHAR(255) NOT NULL,
  method VARCHAR(10) NOT NULL,
  required_role VARCHAR(50) NOT NULL
);
