name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build (backend)
        run: ./mvnw -B -DskipITs=true verify

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: release-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: release-ui/package-lock.json
      - run: npm ci
      - run: npm run build
